/*
 * Centricity MF Screener Dashboard — data-loader.js
 *
 * The single API surface that every page consumes. No framework, no build
 * step. Loads cycle JSONs lazily, caches by date, exposes filtering/formatting
 * helpers and the canonical recompute function used by the weight drawer.
 *
 * Exposes window.DataLoader.
 *
 * Locked behaviours (per Cowork direction 2026-05-05):
 *
 *   1. lazy-load only, never preload. loadCycle('YYYY-MM-DD') fetches
 *      data/screener-YYYY-MM-DD.json and caches it in a single in-memory
 *      Map. Switching cycles is a fetch-or-cache call; the Archive screen
 *      never holds the full history in memory.
 *
 *   2. listCycles() reads data/manifest.json which is generated by the
 *      GitHub Action on every push (Step 5). The converter is deliberately
 *      NOT responsible for the manifest — its job is "one Excel → one
 *      JSON, deterministic"; the manifest is a repo-state aggregate.
 *      Until the Action ships, listCycles() falls back to a single
 *      bootstrap entry so the dashboard renders during local dev.
 *
 *   3. recomputeScore(fund, weights) returns null when the fund is not
 *      Ranked. Non-Ranked funds (1-3yr Warning, New Fund Monitoring) must
 *      never display a recomputed score; the UI shows the appropriate
 *      badge instead. Caller-side null-checks against the centricity_score
 *      field do the right thing.
 *
 *   4. The weight drawer enumerates parameters strictly from
 *      cycle_meta.scoring_weights[] order. Per CLAUDE.md §9 rule 1, no
 *      hardcoded parameter list anywhere in the UI; if the Excel adds or
 *      removes a parameter next cycle, the drawer auto-resizes.
 *
 *   5. Recompute formula is the same one the converter asserts at build
 *      time:  score = Σ(parameter_scores[p] × weight_pct[p]) / 100.
 *      Since the converter has already verified every Ranked fund matches
 *      the stored Excel score within ±0.0001, recomputing here against
 *      ANY weight set produces a score numerically consistent with the
 *      Excel category-sheet formula. No re-percentile-ing on the client.
 */
(function () {
  'use strict';

  /* -------------------------------------------------------- *
   *  In-memory caches
   * -------------------------------------------------------- */
  /** @type {Map<string, object>}  cycleDate (YYYY-MM-DD) -> full cycle JSON */
  const cycleCache = new Map();
  /** @type {object|null}  loaded once from data/manifest.json */
  let manifestCache = null;

  /* -------------------------------------------------------- *
   *  loadCycle — lazy fetch + cache
   * -------------------------------------------------------- */
  /**
   * Fetch and cache a single cycle's JSON.
   * @param {string} cycleDate ISO date 'YYYY-MM-DD'
   * @returns {Promise<object>} the cycle JSON
   * @throws {Error} on network or 4xx/5xx
   */
  async function loadCycle(cycleDate) {
    if (!cycleDate) throw new Error('loadCycle: cycleDate required');
    if (cycleCache.has(cycleDate)) return cycleCache.get(cycleDate);
    const res = await fetch(`data/screener-${cycleDate}.json`, { cache: 'default' });
    if (!res.ok) {
      throw new Error(`loadCycle: HTTP ${res.status} for ${cycleDate}`);
    }
    const data = await res.json();
    cycleCache.set(cycleDate, data);
    return data;
  }

  /**
   * Return the list of dates currently cached. Useful for diagnostics.
   * @returns {string[]}
   */
  function getCachedCycles() {
    return Array.from(cycleCache.keys()).sort();
  }

  /* -------------------------------------------------------- *
   *  listCycles — manifest read (with bootstrap fallback)
   * -------------------------------------------------------- */
  /**
   * List every cycle the dashboard has data for.
   * Reads data/manifest.json (auto-generated by GitHub Action on push).
   * If the manifest doesn't exist yet (local dev before Step 5 ships
   * the Action), falls back to a single bootstrap entry so pages render.
   *
   * Manifest shape (Action will produce this):
   *   { generated_at: ISO,
   *     latest: 'YYYY-MM-DD',
   *     cycles: [ { date: 'YYYY-MM-DD', label: 'U2 Apr 2026', size_bytes: 2_240_715 }, ... ] }
   *
   * @returns {Promise<object>}
   */
  async function listCycles() {
    if (manifestCache) return manifestCache;
    try {
      const res = await fetch('data/manifest.json', { cache: 'default' });
      if (res.ok) {
        manifestCache = await res.json();
        return manifestCache;
      }
    } catch (e) {
      // network error or no manifest yet — fall through to bootstrap
    }
    manifestCache = {
      generated_at: null,
      latest: '2026-04-15',
      cycles: [{ date: '2026-04-15', label: 'U2 Apr 2026' }],
      _source: 'bootstrap',  // GitHub Action will overwrite with _source: 'action'
    };
    return manifestCache;
  }

  /* -------------------------------------------------------- *
   *  recomputeScore — the canonical weight-drawer formula
   * -------------------------------------------------------- */
  /**
   * Recompute centricity_score from parameter_scores × weights.
   * Mirrors the converter's build-time assertion exactly.
   *
   * @param {object} fund                   one entry from cycle.funds[]
   * @param {Array<{parameter,weight_pct}>} weights  cycle_meta.scoring_weights or a user-edited copy
   * @returns {number|null} 0..1 score, or null when fund is not Ranked
   */
  function recomputeScore(fund, weights) {
    if (!fund || fund.centricity_score_status !== 'Ranked') return null;
    if (!Array.isArray(weights) || weights.length === 0) return null;
    if (!fund.parameter_scores) return null;
    let sum = 0;
    for (const w of weights) {
      const ps = fund.parameter_scores[w.parameter];
      if (ps == null) continue;  // ISNUMBER drops the param from the numerator;
                                 // denominator stays at 100 per mf-whitelisting §4.2
      sum += ps * (w.weight_pct ?? 0);
    }
    // 6 decimal places — matches the converter's storage precision
    return Math.round((sum / 100) * 1e6) / 1e6;
  }

  /* -------------------------------------------------------- *
   *  Filtering / selection
   * -------------------------------------------------------- */
  /**
   * Return funds matching simple filter criteria.
   *
   * @param {object} cycle     full cycle JSON (from loadCycle)
   * @param {object} [opts]
   * @param {string|string[]} [opts.category]    one of the 26 SEBI categories
   * @param {string|string[]} [opts.sub_class]   'Equity' | 'Hybrid'
   * @param {string|string[]} [opts.status]      'Ranked' | '1-3yr Warning' | 'New Fund Monitoring'
   * @param {string} [opts.amc]
   * @param {string} [opts.searchText]           substring match against fund_name, amc, scheme_code
   * @param {string} [opts.sortBy]               dotted path, e.g. 'centricity_rank_overall' or 'risk_metrics.sharpe_3y'
   * @param {string} [opts.sortDir]              'asc' (default) | 'desc'
   * @param {number} [opts.limit]
   * @returns {object[]}
   */
  function getFunds(cycle, opts) {
    if (!cycle || !Array.isArray(cycle.funds)) return [];
    opts = opts || {};
    let funds = cycle.funds.slice();

    const matchSet = (val, target) => {
      if (target == null) return true;
      if (Array.isArray(target)) return target.includes(val);
      return val === target;
    };

    if (opts.category)  funds = funds.filter(f => matchSet(f.category, opts.category));
    if (opts.sub_class) funds = funds.filter(f => matchSet(f.sub_category_class, opts.sub_class));
    if (opts.status)    funds = funds.filter(f => matchSet(f.centricity_score_status, opts.status));
    if (opts.amc)       funds = funds.filter(f => f.amc === opts.amc);

    if (opts.searchText) {
      const q = String(opts.searchText).toLowerCase().trim();
      if (q) {
        funds = funds.filter(f =>
          (f.fund_name || '').toLowerCase().includes(q) ||
          (f.amc || '').toLowerCase().includes(q) ||
          String(f.scheme_code || '').includes(q)
        );
      }
    }

    if (opts.sortBy) {
      const dir = opts.sortDir === 'desc' ? -1 : 1;
      funds.sort((a, b) => {
        const av = pluck(a, opts.sortBy);
        const bv = pluck(b, opts.sortBy);
        if (av == null && bv == null) return 0;
        if (av == null) return 1;     // nulls sort last regardless of direction
        if (bv == null) return -1;
        if (av < bv) return -1 * dir;
        if (av > bv) return 1 * dir;
        return 0;
      });
    }

    if (opts.limit) funds = funds.slice(0, opts.limit);
    return funds;
  }

  /**
   * Lookup by AMFI scheme code.
   * @returns {object|null}
   */
  function getFund(cycle, schemeCode) {
    if (!cycle || !Array.isArray(cycle.funds)) return null;
    const code = Number(schemeCode);
    return cycle.funds.find(f => f.scheme_code === code) || null;
  }

  /**
   * Top-N by overall Centricity rank (1 = best).
   * Only considers Ranked funds.
   */
  function topByOverallRank(cycle, n) {
    n = n || 10;
    return getFunds(cycle, {
      status: 'Ranked',
      sortBy: 'centricity_rank_overall',
      sortDir: 'asc',
      limit: n,
    });
  }

  /**
   * Top-N by recomputed score using a custom weight set
   * (the weight drawer's primary call). Falls back to stored
   * centricity_rank_overall when weights are equal to defaults.
   */
  function topByCustomWeights(cycle, weights, n) {
    n = n || 10;
    const ranked = getFunds(cycle, { status: 'Ranked' });
    const scored = ranked.map(f => ({
      fund: f,
      score: recomputeScore(f, weights),
    })).filter(x => x.score != null);
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, n).map(x => x.fund);
  }

  /* -------------------------------------------------------- *
   *  Formatters
   * -------------------------------------------------------- */
  /**
   * Indian comma grouping for ₹ Cr. Brand Standards §5.
   * fmtINR(12345.67) -> "12,346"   fmtINR(123456.7) -> "1,23,457"
   */
  function fmtINR(n) {
    if (n == null || isNaN(n)) return '—';
    const r = Math.round(Number(n));
    const s = Math.abs(r).toString();
    const last3 = s.slice(-3);
    const rest = s.slice(0, -3);
    const grouped = rest.replace(/\B(?=(\d{2})+(?!\d))/g, ',');
    const out = (grouped ? grouped + ',' : '') + last3;
    return r < 0 ? '-' + out : out;
  }

  /**
   * Percent with sign and decimals; em-dash for null/NaN.
   * fmtPct(12.34) -> "+12.34%"   fmtPct(-3.5) -> "−3.50%"   fmtPct(null) -> "—"
   * Negative sign uses Unicode minus (U+2212) per Brand Standards typography.
   */
  function fmtPct(n, decimals) {
    if (n == null || isNaN(n)) return '—';
    if (decimals == null) decimals = 2;
    const v = Number(n);
    if (v === 0) return v.toFixed(decimals) + '%';
    const sign = v > 0 ? '+' : '−';
    return sign + Math.abs(v).toFixed(decimals) + '%';
  }

  /**
   * Plain number with decimals; em-dash for null.
   * fmtNum(0.7684) -> "0.77"
   */
  function fmtNum(n, decimals) {
    if (n == null || isNaN(n)) return '—';
    if (decimals == null) decimals = 2;
    return Number(n).toFixed(decimals);
  }

  /**
   * Centricity score as an absolute percentage. Distinct from fmtPct() which
   * forces a +/− sign — score values are always non-negative absolutes, so
   * a sign is wrong. fmtScorePct(0.8789) -> "87.89%"; null/NaN -> "—".
   */
  function fmtScorePct(n, decimals) {
    if (n == null || isNaN(n)) return '—';
    if (decimals == null) decimals = 2;
    return (Number(n) * 100).toFixed(decimals) + '%';
  }

  /**
   * "DD MMM YYYY" — Brand Standards §5 (no DD/MM/YYYY ever).
   * Accepts an ISO 'YYYY-MM-DD' string or a Date.
   */
  function fmtDate(iso) {
    if (!iso) return '—';
    let d;
    if (iso instanceof Date) {
      d = iso;
    } else {
      const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(iso));
      if (!m) return '—';
      d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]));
    }
    if (isNaN(d.getTime())) return '—';
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return `${String(d.getUTCDate()).padStart(2, '0')} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
  }

  /**
   * Returns the CSS class for a numeric cell — 'num' or 'num neg'.
   * Negative-only Dark Red per Brand Standards §2.
   */
  function pctClass(n) {
    return (n != null && !isNaN(n) && Number(n) < 0) ? 'num neg' : 'num';
  }

  /* -------------------------------------------------------- *
   *  Internal helpers
   * -------------------------------------------------------- */
  function pluck(obj, path) {
    if (obj == null) return null;
    return String(path).split('.').reduce(
      (o, k) => (o == null ? null : o[k]), obj
    );
  }

  /* -------------------------------------------------------- *
   *  Public API
   * -------------------------------------------------------- */
  window.DataLoader = {
    // Loaders
    loadCycle,
    listCycles,
    getCachedCycles,
    // Selectors
    getFund,
    getFunds,
    topByOverallRank,
    topByCustomWeights,
    // Recompute
    recomputeScore,
    // Formatters
    fmtINR,
    fmtPct,
    fmtNum,
    fmtScorePct,
    fmtDate,
    pctClass,
  };
})();
